//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
  hero: Hero;
  heroConnection: HeroConnection;
  about: About;
  aboutConnection: AboutConnection;
  products: Products;
  productsConnection: ProductsConnection;
  features: Features;
  featuresConnection: FeaturesConnection;
  specs: Specs;
  specsConnection: SpecsConnection;
  certifications: Certifications;
  certificationsConnection: CertificationsConnection;
  globalPresence: GlobalPresence;
  globalPresenceConnection: GlobalPresenceConnection;
  contact: Contact;
  contactConnection: ContactConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};


export type QueryHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
};


export type QueryAboutArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
};


export type QueryProductsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProductsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProductsFilter>;
};


export type QueryFeaturesArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFeaturesConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturesFilter>;
};


export type QuerySpecsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySpecsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SpecsFilter>;
};


export type QueryCertificationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCertificationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CertificationsFilter>;
};


export type QueryGlobalPresenceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGlobalPresenceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalPresenceFilter>;
};


export type QueryContactArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
};

export type DocumentFilter = {
  siteSettings?: InputMaybe<SiteSettingsFilter>;
  hero?: InputMaybe<HeroFilter>;
  about?: InputMaybe<AboutFilter>;
  products?: InputMaybe<ProductsFilter>;
  features?: InputMaybe<FeaturesFilter>;
  specs?: InputMaybe<SpecsFilter>;
  certifications?: InputMaybe<CertificationsFilter>;
  globalPresence?: InputMaybe<GlobalPresenceFilter>;
  contact?: InputMaybe<ContactFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = SiteSettings | Hero | About | Products | Features | Specs | Certifications | GlobalPresence | Contact | Folder;

export type SiteSettingsNavigationLinks = {
  __typename?: 'SiteSettingsNavigationLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type SiteSettingsNavigation = {
  __typename?: 'SiteSettingsNavigation';
  links?: Maybe<Array<Maybe<SiteSettingsNavigationLinks>>>;
  ctaText?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<Scalars['String']['output']>;
};

export type SiteSettingsFooterColumnsLinks = {
  __typename?: 'SiteSettingsFooterColumnsLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
};

export type SiteSettingsFooterColumns = {
  __typename?: 'SiteSettingsFooterColumns';
  title?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<SiteSettingsFooterColumnsLinks>>>;
};

export type SiteSettingsFooter = {
  __typename?: 'SiteSettingsFooter';
  description?: Maybe<Scalars['String']['output']>;
  columns?: Maybe<Array<Maybe<SiteSettingsFooterColumns>>>;
};

export type SiteSettingsSeo = {
  __typename?: 'SiteSettingsSeo';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  siteName: Scalars['String']['output'];
  navigation?: Maybe<SiteSettingsNavigation>;
  footer?: Maybe<SiteSettingsFooter>;
  seo?: Maybe<SiteSettingsSeo>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSettingsNavigationLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SiteSettingsNavigationFilter = {
  links?: InputMaybe<SiteSettingsNavigationLinksFilter>;
  ctaText?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<StringFilter>;
};

export type SiteSettingsFooterColumnsLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type SiteSettingsFooterColumnsFilter = {
  title?: InputMaybe<StringFilter>;
  links?: InputMaybe<SiteSettingsFooterColumnsLinksFilter>;
};

export type SiteSettingsFooterFilter = {
  description?: InputMaybe<StringFilter>;
  columns?: InputMaybe<SiteSettingsFooterColumnsFilter>;
};

export type SiteSettingsSeoFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SiteSettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  navigation?: InputMaybe<SiteSettingsNavigationFilter>;
  footer?: InputMaybe<SiteSettingsFooterFilter>;
  seo?: InputMaybe<SiteSettingsSeoFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type HeroCta = {
  __typename?: 'HeroCta';
  primaryText?: Maybe<Scalars['String']['output']>;
  primaryLink?: Maybe<Scalars['String']['output']>;
  secondaryText?: Maybe<Scalars['String']['output']>;
  secondaryLink?: Maybe<Scalars['String']['output']>;
};

export type HeroStats = {
  __typename?: 'HeroStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type Hero = Node & Document & {
  __typename?: 'Hero';
  badge?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  titleSuffix?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  cta?: Maybe<HeroCta>;
  stats?: Maybe<Array<Maybe<HeroStats>>>;
  image?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HeroCtaFilter = {
  primaryText?: InputMaybe<StringFilter>;
  primaryLink?: InputMaybe<StringFilter>;
  secondaryText?: InputMaybe<StringFilter>;
  secondaryLink?: InputMaybe<StringFilter>;
};

export type HeroStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type HeroFilter = {
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  titleSuffix?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cta?: InputMaybe<HeroCtaFilter>;
  stats?: InputMaybe<HeroStatsFilter>;
  image?: InputMaybe<StringFilter>;
};

export type HeroConnectionEdges = {
  __typename?: 'HeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero>;
};

export type HeroConnection = Connection & {
  __typename?: 'HeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeroConnectionEdges>>>;
};

export type AboutFeatures = {
  __typename?: 'AboutFeatures';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type About = Node & Document & {
  __typename?: 'About';
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  paragraph1?: Maybe<Scalars['String']['output']>;
  paragraph2?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<AboutFeatures>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutFeaturesFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutFilter = {
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  paragraph1?: InputMaybe<StringFilter>;
  paragraph2?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  features?: InputMaybe<AboutFeaturesFilter>;
};

export type AboutConnectionEdges = {
  __typename?: 'AboutConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<About>;
};

export type AboutConnection = Connection & {
  __typename?: 'AboutConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutConnectionEdges>>>;
};

export type ProductsFeatures = {
  __typename?: 'ProductsFeatures';
  text?: Maybe<Scalars['String']['output']>;
};

export type Products = Node & Document & {
  __typename?: 'Products';
  badge?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  features?: Maybe<Array<Maybe<ProductsFeatures>>>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProductsFeaturesFilter = {
  text?: InputMaybe<StringFilter>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ProductsFilter = {
  badge?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  features?: InputMaybe<ProductsFeaturesFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ProductsConnectionEdges = {
  __typename?: 'ProductsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Products>;
};

export type ProductsConnection = Connection & {
  __typename?: 'ProductsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProductsConnectionEdges>>>;
};

export type FeaturesItems = {
  __typename?: 'FeaturesItems';
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  iconName?: Maybe<Scalars['String']['output']>;
};

export type Features = Node & Document & {
  __typename?: 'Features';
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<FeaturesItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FeaturesItemsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  iconName?: InputMaybe<StringFilter>;
};

export type FeaturesFilter = {
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  items?: InputMaybe<FeaturesItemsFilter>;
};

export type FeaturesConnectionEdges = {
  __typename?: 'FeaturesConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Features>;
};

export type FeaturesConnection = Connection & {
  __typename?: 'FeaturesConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FeaturesConnectionEdges>>>;
};

export type SpecsItems = {
  __typename?: 'SpecsItems';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Specs = Node & Document & {
  __typename?: 'Specs';
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<SpecsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SpecsItemsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SpecsFilter = {
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  items?: InputMaybe<SpecsItemsFilter>;
};

export type SpecsConnectionEdges = {
  __typename?: 'SpecsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Specs>;
};

export type SpecsConnection = Connection & {
  __typename?: 'SpecsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SpecsConnectionEdges>>>;
};

export type CertificationsItems = {
  __typename?: 'CertificationsItems';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  iconName?: Maybe<Scalars['String']['output']>;
  badgeImage?: Maybe<Scalars['String']['output']>;
};

export type Certifications = Node & Document & {
  __typename?: 'Certifications';
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<CertificationsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CertificationsItemsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  iconName?: InputMaybe<StringFilter>;
  badgeImage?: InputMaybe<StringFilter>;
};

export type CertificationsFilter = {
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  items?: InputMaybe<CertificationsItemsFilter>;
};

export type CertificationsConnectionEdges = {
  __typename?: 'CertificationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Certifications>;
};

export type CertificationsConnection = Connection & {
  __typename?: 'CertificationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CertificationsConnectionEdges>>>;
};

export type GlobalPresenceRegions = {
  __typename?: 'GlobalPresenceRegions';
  name?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type GlobalPresenceStats = {
  __typename?: 'GlobalPresenceStats';
  value?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type GlobalPresence = Node & Document & {
  __typename?: 'GlobalPresence';
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  mapImage?: Maybe<Scalars['String']['output']>;
  regions?: Maybe<Array<Maybe<GlobalPresenceRegions>>>;
  stats?: Maybe<Array<Maybe<GlobalPresenceStats>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GlobalPresenceRegionsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type GlobalPresenceStatsFilter = {
  value?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type GlobalPresenceFilter = {
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  mapImage?: InputMaybe<StringFilter>;
  regions?: InputMaybe<GlobalPresenceRegionsFilter>;
  stats?: InputMaybe<GlobalPresenceStatsFilter>;
};

export type GlobalPresenceConnectionEdges = {
  __typename?: 'GlobalPresenceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<GlobalPresence>;
};

export type GlobalPresenceConnection = Connection & {
  __typename?: 'GlobalPresenceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GlobalPresenceConnectionEdges>>>;
};

export type ContactContactCards = {
  __typename?: 'ContactContactCards';
  title?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
  iconName?: Maybe<Scalars['String']['output']>;
};

export type Contact = Node & Document & {
  __typename?: 'Contact';
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  contactCards?: Maybe<Array<Maybe<ContactContactCards>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactContactCardsFilter = {
  title?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
  iconName?: InputMaybe<StringFilter>;
};

export type ContactFilter = {
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  contactCards?: InputMaybe<ContactContactCardsFilter>;
};

export type ContactConnectionEdges = {
  __typename?: 'ContactConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contact>;
};

export type ContactConnection = Connection & {
  __typename?: 'ContactConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
  updateHero: Hero;
  createHero: Hero;
  updateAbout: About;
  createAbout: About;
  updateProducts: Products;
  createProducts: Products;
  updateFeatures: Features;
  createFeatures: Features;
  updateSpecs: Specs;
  createSpecs: Specs;
  updateCertifications: Certifications;
  createCertifications: Certifications;
  updateGlobalPresence: GlobalPresence;
  createGlobalPresence: GlobalPresence;
  updateContact: Contact;
  createContact: Contact;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationUpdateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationCreateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationUpdateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationCreateAboutArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutMutation;
};


export type MutationUpdateProductsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProductsMutation;
};


export type MutationCreateProductsArgs = {
  relativePath: Scalars['String']['input'];
  params: ProductsMutation;
};


export type MutationUpdateFeaturesArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturesMutation;
};


export type MutationCreateFeaturesArgs = {
  relativePath: Scalars['String']['input'];
  params: FeaturesMutation;
};


export type MutationUpdateSpecsArgs = {
  relativePath: Scalars['String']['input'];
  params: SpecsMutation;
};


export type MutationCreateSpecsArgs = {
  relativePath: Scalars['String']['input'];
  params: SpecsMutation;
};


export type MutationUpdateCertificationsArgs = {
  relativePath: Scalars['String']['input'];
  params: CertificationsMutation;
};


export type MutationCreateCertificationsArgs = {
  relativePath: Scalars['String']['input'];
  params: CertificationsMutation;
};


export type MutationUpdateGlobalPresenceArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalPresenceMutation;
};


export type MutationCreateGlobalPresenceArgs = {
  relativePath: Scalars['String']['input'];
  params: GlobalPresenceMutation;
};


export type MutationUpdateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};


export type MutationCreateContactArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactMutation;
};

export type DocumentUpdateMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  hero?: InputMaybe<HeroMutation>;
  about?: InputMaybe<AboutMutation>;
  products?: InputMaybe<ProductsMutation>;
  features?: InputMaybe<FeaturesMutation>;
  specs?: InputMaybe<SpecsMutation>;
  certifications?: InputMaybe<CertificationsMutation>;
  globalPresence?: InputMaybe<GlobalPresenceMutation>;
  contact?: InputMaybe<ContactMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  hero?: InputMaybe<HeroMutation>;
  about?: InputMaybe<AboutMutation>;
  products?: InputMaybe<ProductsMutation>;
  features?: InputMaybe<FeaturesMutation>;
  specs?: InputMaybe<SpecsMutation>;
  certifications?: InputMaybe<CertificationsMutation>;
  globalPresence?: InputMaybe<GlobalPresenceMutation>;
  contact?: InputMaybe<ContactMutation>;
};

export type SiteSettingsNavigationLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsNavigationMutation = {
  links?: InputMaybe<Array<InputMaybe<SiteSettingsNavigationLinksMutation>>>;
  ctaText?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsFooterColumnsLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsFooterColumnsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<SiteSettingsFooterColumnsLinksMutation>>>;
};

export type SiteSettingsFooterMutation = {
  description?: InputMaybe<Scalars['String']['input']>;
  columns?: InputMaybe<Array<InputMaybe<SiteSettingsFooterColumnsMutation>>>;
};

export type SiteSettingsSeoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  navigation?: InputMaybe<SiteSettingsNavigationMutation>;
  footer?: InputMaybe<SiteSettingsFooterMutation>;
  seo?: InputMaybe<SiteSettingsSeoMutation>;
};

export type HeroCtaMutation = {
  primaryText?: InputMaybe<Scalars['String']['input']>;
  primaryLink?: InputMaybe<Scalars['String']['input']>;
  secondaryText?: InputMaybe<Scalars['String']['input']>;
  secondaryLink?: InputMaybe<Scalars['String']['input']>;
};

export type HeroStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type HeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  titleSuffix?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  cta?: InputMaybe<HeroCtaMutation>;
  stats?: InputMaybe<Array<InputMaybe<HeroStatsMutation>>>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type AboutFeaturesMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  paragraph1?: InputMaybe<Scalars['String']['input']>;
  paragraph2?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<AboutFeaturesMutation>>>;
};

export type ProductsFeaturesMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type ProductsMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  features?: InputMaybe<Array<InputMaybe<ProductsFeaturesMutation>>>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type FeaturesItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  iconName?: InputMaybe<Scalars['String']['input']>;
};

export type FeaturesMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<FeaturesItemsMutation>>>;
};

export type SpecsItemsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SpecsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<SpecsItemsMutation>>>;
};

export type CertificationsItemsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  iconName?: InputMaybe<Scalars['String']['input']>;
  badgeImage?: InputMaybe<Scalars['String']['input']>;
};

export type CertificationsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<CertificationsItemsMutation>>>;
};

export type GlobalPresenceRegionsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalPresenceStatsMutation = {
  value?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type GlobalPresenceMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  mapImage?: InputMaybe<Scalars['String']['input']>;
  regions?: InputMaybe<Array<InputMaybe<GlobalPresenceRegionsMutation>>>;
  stats?: InputMaybe<Array<InputMaybe<GlobalPresenceStatsMutation>>>;
};

export type ContactContactCardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
  iconName?: InputMaybe<Scalars['String']['input']>;
};

export type ContactMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  contactCards?: InputMaybe<Array<InputMaybe<ContactContactCardsMutation>>>;
};

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', siteName: string, navigation?: { __typename: 'SiteSettingsNavigation', ctaText?: string | null, ctaLink?: string | null, links?: Array<{ __typename: 'SiteSettingsNavigationLinks', label?: string | null, href?: string | null } | null> | null } | null, footer?: { __typename: 'SiteSettingsFooter', description?: string | null, columns?: Array<{ __typename: 'SiteSettingsFooterColumns', title?: string | null, links?: Array<{ __typename: 'SiteSettingsFooterColumnsLinks', label?: string | null, href?: string | null } | null> | null } | null> | null } | null, seo?: { __typename: 'SiteSettingsSeo', title?: string | null, description?: string | null } | null };

export type HeroPartsFragment = { __typename: 'Hero', badge?: string | null, title?: string | null, titleHighlight?: string | null, titleSuffix?: string | null, description?: string | null, image?: string | null, cta?: { __typename: 'HeroCta', primaryText?: string | null, primaryLink?: string | null, secondaryText?: string | null, secondaryLink?: string | null } | null, stats?: Array<{ __typename: 'HeroStats', value?: string | null, label?: string | null } | null> | null };

export type AboutPartsFragment = { __typename: 'About', label?: string | null, title?: string | null, paragraph1?: string | null, paragraph2?: string | null, image?: string | null, features?: Array<{ __typename: 'AboutFeatures', title?: string | null, description?: string | null } | null> | null };

export type ProductsPartsFragment = { __typename: 'Products', badge?: string | null, title: string, subtitle?: string | null, image?: string | null, order?: number | null, features?: Array<{ __typename: 'ProductsFeatures', text?: string | null } | null> | null };

export type FeaturesPartsFragment = { __typename: 'Features', label?: string | null, title?: string | null, description?: string | null, items?: Array<{ __typename: 'FeaturesItems', title?: string | null, description?: string | null, iconName?: string | null } | null> | null };

export type SpecsPartsFragment = { __typename: 'Specs', label?: string | null, title?: string | null, description?: string | null, items?: Array<{ __typename: 'SpecsItems', value?: string | null, label?: string | null, description?: string | null } | null> | null };

export type CertificationsPartsFragment = { __typename: 'Certifications', label?: string | null, title?: string | null, items?: Array<{ __typename: 'CertificationsItems', name?: string | null, description?: string | null, iconName?: string | null, badgeImage?: string | null } | null> | null };

export type GlobalPresencePartsFragment = { __typename: 'GlobalPresence', label?: string | null, title?: string | null, mapImage?: string | null, regions?: Array<{ __typename: 'GlobalPresenceRegions', name?: string | null, description?: string | null } | null> | null, stats?: Array<{ __typename: 'GlobalPresenceStats', value?: string | null, label?: string | null } | null> | null };

export type ContactPartsFragment = { __typename: 'Contact', label?: string | null, title?: string | null, description?: string | null, contactCards?: Array<{ __typename: 'ContactContactCards', title?: string | null, value?: string | null, iconName?: string | null } | null> | null };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, siteName: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navigation?: { __typename: 'SiteSettingsNavigation', ctaText?: string | null, ctaLink?: string | null, links?: Array<{ __typename: 'SiteSettingsNavigationLinks', label?: string | null, href?: string | null } | null> | null } | null, footer?: { __typename: 'SiteSettingsFooter', description?: string | null, columns?: Array<{ __typename: 'SiteSettingsFooterColumns', title?: string | null, links?: Array<{ __typename: 'SiteSettingsFooterColumnsLinks', label?: string | null, href?: string | null } | null> | null } | null> | null } | null, seo?: { __typename: 'SiteSettingsSeo', title?: string | null, description?: string | null } | null } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, siteName: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, navigation?: { __typename: 'SiteSettingsNavigation', ctaText?: string | null, ctaLink?: string | null, links?: Array<{ __typename: 'SiteSettingsNavigationLinks', label?: string | null, href?: string | null } | null> | null } | null, footer?: { __typename: 'SiteSettingsFooter', description?: string | null, columns?: Array<{ __typename: 'SiteSettingsFooterColumns', title?: string | null, links?: Array<{ __typename: 'SiteSettingsFooterColumnsLinks', label?: string | null, href?: string | null } | null> | null } | null> | null } | null, seo?: { __typename: 'SiteSettingsSeo', title?: string | null, description?: string | null } | null } | null } | null> | null } };

export type HeroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeroQuery = { __typename?: 'Query', hero: { __typename: 'Hero', id: string, badge?: string | null, title?: string | null, titleHighlight?: string | null, titleSuffix?: string | null, description?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cta?: { __typename: 'HeroCta', primaryText?: string | null, primaryLink?: string | null, secondaryText?: string | null, secondaryLink?: string | null } | null, stats?: Array<{ __typename: 'HeroStats', value?: string | null, label?: string | null } | null> | null } };

export type HeroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
}>;


export type HeroConnectionQuery = { __typename?: 'Query', heroConnection: { __typename?: 'HeroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeroConnectionEdges', cursor: string, node?: { __typename: 'Hero', id: string, badge?: string | null, title?: string | null, titleHighlight?: string | null, titleSuffix?: string | null, description?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, cta?: { __typename: 'HeroCta', primaryText?: string | null, primaryLink?: string | null, secondaryText?: string | null, secondaryLink?: string | null } | null, stats?: Array<{ __typename: 'HeroStats', value?: string | null, label?: string | null } | null> | null } | null } | null> | null } };

export type AboutQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutQuery = { __typename?: 'Query', about: { __typename: 'About', id: string, label?: string | null, title?: string | null, paragraph1?: string | null, paragraph2?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'AboutFeatures', title?: string | null, description?: string | null } | null> | null } };

export type AboutConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutFilter>;
}>;


export type AboutConnectionQuery = { __typename?: 'Query', aboutConnection: { __typename?: 'AboutConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutConnectionEdges', cursor: string, node?: { __typename: 'About', id: string, label?: string | null, title?: string | null, paragraph1?: string | null, paragraph2?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'AboutFeatures', title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type ProductsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProductsQuery = { __typename?: 'Query', products: { __typename: 'Products', id: string, badge?: string | null, title: string, subtitle?: string | null, image?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'ProductsFeatures', text?: string | null } | null> | null } };

export type ProductsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProductsFilter>;
}>;


export type ProductsConnectionQuery = { __typename?: 'Query', productsConnection: { __typename?: 'ProductsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProductsConnectionEdges', cursor: string, node?: { __typename: 'Products', id: string, badge?: string | null, title: string, subtitle?: string | null, image?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, features?: Array<{ __typename: 'ProductsFeatures', text?: string | null } | null> | null } | null } | null> | null } };

export type FeaturesQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FeaturesQuery = { __typename?: 'Query', features: { __typename: 'Features', id: string, label?: string | null, title?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FeaturesItems', title?: string | null, description?: string | null, iconName?: string | null } | null> | null } };

export type FeaturesConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FeaturesFilter>;
}>;


export type FeaturesConnectionQuery = { __typename?: 'Query', featuresConnection: { __typename?: 'FeaturesConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FeaturesConnectionEdges', cursor: string, node?: { __typename: 'Features', id: string, label?: string | null, title?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'FeaturesItems', title?: string | null, description?: string | null, iconName?: string | null } | null> | null } | null } | null> | null } };

export type SpecsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SpecsQuery = { __typename?: 'Query', specs: { __typename: 'Specs', id: string, label?: string | null, title?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'SpecsItems', value?: string | null, label?: string | null, description?: string | null } | null> | null } };

export type SpecsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SpecsFilter>;
}>;


export type SpecsConnectionQuery = { __typename?: 'Query', specsConnection: { __typename?: 'SpecsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SpecsConnectionEdges', cursor: string, node?: { __typename: 'Specs', id: string, label?: string | null, title?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'SpecsItems', value?: string | null, label?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type CertificationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CertificationsQuery = { __typename?: 'Query', certifications: { __typename: 'Certifications', id: string, label?: string | null, title?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'CertificationsItems', name?: string | null, description?: string | null, iconName?: string | null, badgeImage?: string | null } | null> | null } };

export type CertificationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CertificationsFilter>;
}>;


export type CertificationsConnectionQuery = { __typename?: 'Query', certificationsConnection: { __typename?: 'CertificationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CertificationsConnectionEdges', cursor: string, node?: { __typename: 'Certifications', id: string, label?: string | null, title?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'CertificationsItems', name?: string | null, description?: string | null, iconName?: string | null, badgeImage?: string | null } | null> | null } | null } | null> | null } };

export type GlobalPresenceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GlobalPresenceQuery = { __typename?: 'Query', globalPresence: { __typename: 'GlobalPresence', id: string, label?: string | null, title?: string | null, mapImage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, regions?: Array<{ __typename: 'GlobalPresenceRegions', name?: string | null, description?: string | null } | null> | null, stats?: Array<{ __typename: 'GlobalPresenceStats', value?: string | null, label?: string | null } | null> | null } };

export type GlobalPresenceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GlobalPresenceFilter>;
}>;


export type GlobalPresenceConnectionQuery = { __typename?: 'Query', globalPresenceConnection: { __typename?: 'GlobalPresenceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GlobalPresenceConnectionEdges', cursor: string, node?: { __typename: 'GlobalPresence', id: string, label?: string | null, title?: string | null, mapImage?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, regions?: Array<{ __typename: 'GlobalPresenceRegions', name?: string | null, description?: string | null } | null> | null, stats?: Array<{ __typename: 'GlobalPresenceStats', value?: string | null, label?: string | null } | null> | null } | null } | null> | null } };

export type ContactQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactQuery = { __typename?: 'Query', contact: { __typename: 'Contact', id: string, label?: string | null, title?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contactCards?: Array<{ __typename: 'ContactContactCards', title?: string | null, value?: string | null, iconName?: string | null } | null> | null } };

export type ContactConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactFilter>;
}>;


export type ContactConnectionQuery = { __typename?: 'Query', contactConnection: { __typename?: 'ContactConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactConnectionEdges', cursor: string, node?: { __typename: 'Contact', id: string, label?: string | null, title?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, contactCards?: Array<{ __typename: 'ContactContactCards', title?: string | null, value?: string | null, iconName?: string | null } | null> | null } | null } | null> | null } };

export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  siteName
  navigation {
    __typename
    links {
      __typename
      label
      href
    }
    ctaText
    ctaLink
  }
  footer {
    __typename
    description
    columns {
      __typename
      title
      links {
        __typename
        label
        href
      }
    }
  }
  seo {
    __typename
    title
    description
  }
}
    `;
export const HeroPartsFragmentDoc = gql`
    fragment HeroParts on Hero {
  __typename
  badge
  title
  titleHighlight
  titleSuffix
  description
  cta {
    __typename
    primaryText
    primaryLink
    secondaryText
    secondaryLink
  }
  stats {
    __typename
    value
    label
  }
  image
}
    `;
export const AboutPartsFragmentDoc = gql`
    fragment AboutParts on About {
  __typename
  label
  title
  paragraph1
  paragraph2
  image
  features {
    __typename
    title
    description
  }
}
    `;
export const ProductsPartsFragmentDoc = gql`
    fragment ProductsParts on Products {
  __typename
  badge
  title
  subtitle
  image
  features {
    __typename
    text
  }
  order
}
    `;
export const FeaturesPartsFragmentDoc = gql`
    fragment FeaturesParts on Features {
  __typename
  label
  title
  description
  items {
    __typename
    title
    description
    iconName
  }
}
    `;
export const SpecsPartsFragmentDoc = gql`
    fragment SpecsParts on Specs {
  __typename
  label
  title
  description
  items {
    __typename
    value
    label
    description
  }
}
    `;
export const CertificationsPartsFragmentDoc = gql`
    fragment CertificationsParts on Certifications {
  __typename
  label
  title
  items {
    __typename
    name
    description
    iconName
    badgeImage
  }
}
    `;
export const GlobalPresencePartsFragmentDoc = gql`
    fragment GlobalPresenceParts on GlobalPresence {
  __typename
  label
  title
  mapImage
  regions {
    __typename
    name
    description
  }
  stats {
    __typename
    value
    label
  }
}
    `;
export const ContactPartsFragmentDoc = gql`
    fragment ContactParts on Contact {
  __typename
  label
  title
  description
  contactCards {
    __typename
    title
    value
    iconName
  }
}
    `;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const HeroDocument = gql`
    query hero($relativePath: String!) {
  hero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeroParts
  }
}
    ${HeroPartsFragmentDoc}`;
export const HeroConnectionDocument = gql`
    query heroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeroFilter) {
  heroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeroParts
      }
    }
  }
}
    ${HeroPartsFragmentDoc}`;
export const AboutDocument = gql`
    query about($relativePath: String!) {
  about(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutParts
  }
}
    ${AboutPartsFragmentDoc}`;
export const AboutConnectionDocument = gql`
    query aboutConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutFilter) {
  aboutConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutParts
      }
    }
  }
}
    ${AboutPartsFragmentDoc}`;
export const ProductsDocument = gql`
    query products($relativePath: String!) {
  products(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProductsParts
  }
}
    ${ProductsPartsFragmentDoc}`;
export const ProductsConnectionDocument = gql`
    query productsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProductsFilter) {
  productsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProductsParts
      }
    }
  }
}
    ${ProductsPartsFragmentDoc}`;
export const FeaturesDocument = gql`
    query features($relativePath: String!) {
  features(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FeaturesParts
  }
}
    ${FeaturesPartsFragmentDoc}`;
export const FeaturesConnectionDocument = gql`
    query featuresConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FeaturesFilter) {
  featuresConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FeaturesParts
      }
    }
  }
}
    ${FeaturesPartsFragmentDoc}`;
export const SpecsDocument = gql`
    query specs($relativePath: String!) {
  specs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SpecsParts
  }
}
    ${SpecsPartsFragmentDoc}`;
export const SpecsConnectionDocument = gql`
    query specsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SpecsFilter) {
  specsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SpecsParts
      }
    }
  }
}
    ${SpecsPartsFragmentDoc}`;
export const CertificationsDocument = gql`
    query certifications($relativePath: String!) {
  certifications(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CertificationsParts
  }
}
    ${CertificationsPartsFragmentDoc}`;
export const CertificationsConnectionDocument = gql`
    query certificationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CertificationsFilter) {
  certificationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CertificationsParts
      }
    }
  }
}
    ${CertificationsPartsFragmentDoc}`;
export const GlobalPresenceDocument = gql`
    query globalPresence($relativePath: String!) {
  globalPresence(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GlobalPresenceParts
  }
}
    ${GlobalPresencePartsFragmentDoc}`;
export const GlobalPresenceConnectionDocument = gql`
    query globalPresenceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GlobalPresenceFilter) {
  globalPresenceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GlobalPresenceParts
      }
    }
  }
}
    ${GlobalPresencePartsFragmentDoc}`;
export const ContactDocument = gql`
    query contact($relativePath: String!) {
  contact(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactParts
  }
}
    ${ContactPartsFragmentDoc}`;
export const ContactConnectionDocument = gql`
    query contactConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactFilter) {
  contactConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactParts
      }
    }
  }
}
    ${ContactPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      },
    hero(variables: HeroQueryVariables, options?: C): Promise<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}> {
        return requester<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}, HeroQueryVariables>(HeroDocument, variables, options);
      },
    heroConnection(variables?: HeroConnectionQueryVariables, options?: C): Promise<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}> {
        return requester<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}, HeroConnectionQueryVariables>(HeroConnectionDocument, variables, options);
      },
    about(variables: AboutQueryVariables, options?: C): Promise<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}> {
        return requester<{data: AboutQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutQueryVariables, query: string}, AboutQueryVariables>(AboutDocument, variables, options);
      },
    aboutConnection(variables?: AboutConnectionQueryVariables, options?: C): Promise<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}> {
        return requester<{data: AboutConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutConnectionQueryVariables, query: string}, AboutConnectionQueryVariables>(AboutConnectionDocument, variables, options);
      },
    products(variables: ProductsQueryVariables, options?: C): Promise<{data: ProductsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsQueryVariables, query: string}> {
        return requester<{data: ProductsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsQueryVariables, query: string}, ProductsQueryVariables>(ProductsDocument, variables, options);
      },
    productsConnection(variables?: ProductsConnectionQueryVariables, options?: C): Promise<{data: ProductsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsConnectionQueryVariables, query: string}> {
        return requester<{data: ProductsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProductsConnectionQueryVariables, query: string}, ProductsConnectionQueryVariables>(ProductsConnectionDocument, variables, options);
      },
    features(variables: FeaturesQueryVariables, options?: C): Promise<{data: FeaturesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesQueryVariables, query: string}> {
        return requester<{data: FeaturesQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesQueryVariables, query: string}, FeaturesQueryVariables>(FeaturesDocument, variables, options);
      },
    featuresConnection(variables?: FeaturesConnectionQueryVariables, options?: C): Promise<{data: FeaturesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesConnectionQueryVariables, query: string}> {
        return requester<{data: FeaturesConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FeaturesConnectionQueryVariables, query: string}, FeaturesConnectionQueryVariables>(FeaturesConnectionDocument, variables, options);
      },
    specs(variables: SpecsQueryVariables, options?: C): Promise<{data: SpecsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpecsQueryVariables, query: string}> {
        return requester<{data: SpecsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpecsQueryVariables, query: string}, SpecsQueryVariables>(SpecsDocument, variables, options);
      },
    specsConnection(variables?: SpecsConnectionQueryVariables, options?: C): Promise<{data: SpecsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpecsConnectionQueryVariables, query: string}> {
        return requester<{data: SpecsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SpecsConnectionQueryVariables, query: string}, SpecsConnectionQueryVariables>(SpecsConnectionDocument, variables, options);
      },
    certifications(variables: CertificationsQueryVariables, options?: C): Promise<{data: CertificationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CertificationsQueryVariables, query: string}> {
        return requester<{data: CertificationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CertificationsQueryVariables, query: string}, CertificationsQueryVariables>(CertificationsDocument, variables, options);
      },
    certificationsConnection(variables?: CertificationsConnectionQueryVariables, options?: C): Promise<{data: CertificationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CertificationsConnectionQueryVariables, query: string}> {
        return requester<{data: CertificationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CertificationsConnectionQueryVariables, query: string}, CertificationsConnectionQueryVariables>(CertificationsConnectionDocument, variables, options);
      },
    globalPresence(variables: GlobalPresenceQueryVariables, options?: C): Promise<{data: GlobalPresenceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalPresenceQueryVariables, query: string}> {
        return requester<{data: GlobalPresenceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalPresenceQueryVariables, query: string}, GlobalPresenceQueryVariables>(GlobalPresenceDocument, variables, options);
      },
    globalPresenceConnection(variables?: GlobalPresenceConnectionQueryVariables, options?: C): Promise<{data: GlobalPresenceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalPresenceConnectionQueryVariables, query: string}> {
        return requester<{data: GlobalPresenceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GlobalPresenceConnectionQueryVariables, query: string}, GlobalPresenceConnectionQueryVariables>(GlobalPresenceConnectionDocument, variables, options);
      },
    contact(variables: ContactQueryVariables, options?: C): Promise<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}> {
        return requester<{data: ContactQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactQueryVariables, query: string}, ContactQueryVariables>(ContactDocument, variables, options);
      },
    contactConnection(variables?: ContactConnectionQueryVariables, options?: C): Promise<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}> {
        return requester<{data: ContactConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactConnectionQueryVariables, query: string}, ContactConnectionQueryVariables>(ContactConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  